source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DTAvatarView_Example', :exclusive => true do
  pod "DTAvatarView", :path => "../"
end

target 'DTAvatarView_Tests', :exclusive => true do
  pod "DTAvatarView", :path => "../"

  
end
